# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  # - task: NuGetToolInstaller@1

  # - task: NuGetCommand@2
  #   inputs:
  #     restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Build.SourcesDirectory:"
        Write-Host $(Build.SourcesDirectory)

        Write-Host "Build.Repository.LocalPath:"
        Write-Host $(Build.Repository.LocalPath)

        Write-Host "Agent.BuildDirectory"
        Write-Host $(Agent.BuildDirectory)

        Write-Host "Running jar..."
        java -jar $(Build.SourcesDirectory)/msusel-qatch-csharp-0.1.0-jar-with-dependencies.jar $(Build.SourcesDirectory) $(Build.SourcesDirectory)/qa_out

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/qa_out'
      artifact: 'qa_out_artifact'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: qa_out_artifact
